---
title: "Analysis Section"
author: "Adam Kiehl"
date: "2022-10-11"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Analysis

The relationships between many of the predictors and the response variable of interest, car price, was largely unknown. Aside from a selection of predictors deemed to likely be important based on contextual knowledge, it was not known which predictors should be included in a regression model. Therefore, an array of models were fit using various transformations, variable selection methods, and prior assumptions. All models were fit with the `stan_glm` function in the `rstanarm` package using a Bayesian framework that incorporates prior belief into into traditional regression by use of prior distributions. After fitting, all models were assessed for explanatory power, overfitting, and violations of model assumptions by comparing $R^2$ and $R^2_{LOO}$ and by generating QQ-Normal plots for residuals and residual vs fitted values plots. 

To begin, a full model$^{(1)}$ was fit using the default `stan_glm` priors ($N(0, 6.25)$) to serve as a comparative baseline for future models. The regression intercept was estimated to be $\beta_0 = $ and can be interpreted as the expected price (in dollars) of 3-door, manual, non-metallic, asdjklf fueled car that was pruchased 



- 10 total models were fit
- Various combinations of transformations, predictors, and priors

- Full model, unscaled, with default priors fit as comparative basis
  - Mention coefficient interpretations
- Predictors scaled for interpretation, comparison
- Price log transformed for strictly positive outcome
- Scaled full model fit
  - Mention new coefficient interpretations

- Variable selection performed in several ways
- Horseshoe prior used to place prior mass around 0
  - 11 predictors (questionable month and year), metallic
- LASSO can effectively eliminate predictors
  - Used lasso prior = laplace prior
  - 
- Team-selection predictors based on prior knowledge
  - Default and weakly informative priors
  - 2 sets of interactions explored





